FROM node:24-alpine3.21

WORKDIR /app

ENV NODE_ENV=production
ENV AWS_REGION=us-east-1
ENV DATABASE_URL=postgresql://username:password@localhost/hackhive
ENV DB_HOST=localhost
ENV DB_PORT=5432
ENV DB_DATABASE=hackhive
ENV DB_USER=username
ENV DB_PASS=password
ENV JWT_SECRET=DECOY_JWT_SECRET
ENV ADMIN_TOKEN=DECOY_ADMIN_TOKEN

COPY . .

RUN npm install --include=dev

EXPOSE 8080

ENTRYPOINT [ "npm", "run" ]

CMD [ "dev" ]