FROM ubuntu:22.04

USER root

RUN apt-get update && \
    apt-get install -y \
    curl \
    build-essential \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - && \
    apt-get install -y nodejs && \
    npm install -g npm

WORKDIR /server

COPY package*.json ./

RUN npm install

COPY index.js ./

CMD ["npm", "start"]